### ISSUE TITLE
Option to convert pngs to lossy jpg or jxl?

### ISSUE THREAD

**Issue by arun54321** [Huluti/Curtail#113] opened 2022-03-18 04:19 UTC

**Comment by nekohayo** [comment] 2022-10-29 16:17
Very often I use PNGs as a "working format" to output from GIMP, then need to transcode to JPEG XL (issue #20) for the final archival or publication format. I don't know if this should be considered a duplicate of issue 20 or if this is specifically about being able to transcode from PNG to JXL instead of JPEG to JXL, but I do think that both should be supported, we should be able to transcode from anything to JXL.

**Closed** 2023-04-03 12:01 UTC
Labels: feature-request, out-of-scope?
