### ISSUE TITLE
PNG: "Format of this file is not supported" from one day to the next

### ISSUE THREAD

**Issue by mrmatteastwood** [Huluti/Curtail#189] opened 2023-10-30 12:14 UTC
**Steps to Reproduce:**
1. Launch Curtail (installed as flatpak)
2. Try to compress PNG file

**Current Results:**
"Format of this file is not supported" error message.

**Expected Results:**
File should be compressed.

**Notes:**
- Version 1.7.0, flatpak.
- It was fine yesterday. Same PC, same version of Curtail, I changed literally nothing.
- I looked through ~/.var/app/com.github.huluti.Curtail and couldn't find a log to attach.
- Uninstalled and re-installed the flatpak, same result.
- My PC's complete specs: https://termbin.com/jeum
- When running `flatpak run com.github.huluti.Curtail` from command line and reproducing the issue, I see no error message nor any other output in the terminal.
- Version 1.3.1 from Ubuntu PPA works.
- Latest snap works as well.

**Screenshot:**
![image](https://github.com/Huluti/Curtail/assets/22120259/a0ed960d-f0f9-4e46-968b-41fbcb8245fd)

**File to try:**
Here's the file that I tried compressing in the above screenshot: https://nx30954.your-storageshare.de/s/aFN7ib8cesKxiLe

**Comment by eboye** [comment] 2023-10-31 11:19
Same here. All PNG files I've tried gives the same result.

**Comment by CrimsonFork** [comment] 2023-10-31 21:10
Duplicate of #162.

**Comment by kreaninw** [comment] 2023-11-01 22:47
> Duplicate of #162.

I doubt this issue is a duplicate of issue #162. I use the app to compress PNG files all the time. It just happened recently with version 1.7.

From the release note: **[Switch from OptiPNG to Oxipng](https://github.com/Huluti/Curtail/releases#:~:text=switch%20from%20optipng%20to%20oxipng.)**.  The change likely causes this issue.

**Comment by eboye** [comment] 2023-11-01 22:49
> > Duplicate of #162.
> 
> I doubt this issue is a duplicate of issue #162. I use the app to compress PNG files all the time. It just happened recently with version 1.7.
> 
> From the release note: **[Switch from OptiPNG to Oxipng](https://github.com/Huluti/Curtail/releases#:~:text=switch%20from%20optipng%20to%20oxipng.)**. The change likely causes this issue.

Agree. I literally use it every day for PNG optimizations and it started few days ago. (Probably 1.7, not sure)

**Comment by mrmatteastwood** [comment] 2023-11-02 16:07
Hey guys, I'm wondering if we haven't all been using 1.7.0 since April? It was released on April 5th. I wasn't paying close attention, but I think we've had 1.7.0 on our machines for months and it was something about the flatpak environment that caused the issue to occur. I did have a bunch of flatpak-related updates come through the day before this started happening.

Either way, we can use the Snap for now as a workaround.

**Comment by eboye** [comment] 2023-11-02 16:16
I switched to [pacman](https://archlinux.org/packages/extra/any/curtail/) version for now. But I prefer flatpak. I don't want to install snap just for one app :)

**Comment by Huluti** [comment] 2023-11-03 07:49
Looking into this today :)

**Closed** 2023-11-03 07:57 UTC
Labels: bug

**Comment by Huluti** [comment] 2023-11-03 14:56
Fixed in 1.8.0 available on flathub :)

**Comment by mrmatteastwood** [comment] 2023-11-03 15:14
Fix confirmed. Works great, thanks!

**Comment by eboye** [comment] 2023-11-03 20:18
Yup, fix is working great. Thanks a bunch!
